openapi: '3.0.2'
info:
  title: API Gateway.
  version: '1.0'
servers:
  - url: http://localhost:5000/
components:
  schemas:
    regUserRes:
      type: object
      properties:
        email:
          type: string
          example: 'john@email.com'
        password:
          type: string
          example: '0000Aa'
    regUserReq200:
      type: object
      properties:
        success:
          type: boolean
          example: true
        errors:
          type: array
          example: []
        data:
          type: object
          properties:
            accessToken:
              type: string
              example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5pa3BlY3Nhc0BnbWFpbC5jb20iLCJpZCI6MTcsImlzQWN0aXZhdGVkIjpmYWxzZSwiaWF0IjoxNjczNzczNjQ1LCJleHAiOjE2NzM3NzU0NDV9.uH4OMLBRKjHEuOc_lEWLPuRmAjrPGA02mpMJVESNKdk"
            refreshToken:
              type: boolean
              example: true
        users:
          type: object
          properties:
            email:
              type: string
              example: 'john@email.com'
            id:
              type: integer
              example: 1
            isActivated:
              type: boolean
              example: false

paths:
  /api/registration:
    post:
      description: 'Registration User.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/regUserRes'
      parameters: []
      responses:
        '200':
          description: Successful registration.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/regUserReq200'
        '400':
          description: Bad request.
        '417':
          description: Validation exception.
        '500':
          description: Oops.

  /api/login:
    post:
      description: 'Login User.'
      parameters: []
      responses:
        '200':
          description: OK
  /api/logout:
    post:
      description: 'Logout User.'
      parameters: []
      responses:
        '200':
          description: OK
  /api/activate:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK
  /api/refresh:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK

          
